### ISSUE TITLE
Possible error in schematic

### ISSUE THREAD

**Issue by bzuidgeest** [ddraig68k/hardware#2]
This might be old news to you but when looking at the published schematics for expansion slot 4 I noticed that DTACK_EXT4 is connected to the IRQ pin on slot 4. I read that interrupt on slot 4 is not supported. By the looks of it because you ran out of room on the encoder. However that does not give me a reason to connect dtack to the IRQ pin, so for the moment I am assuming that is an error. Do correct me if I am wrong.

**Comment by ddraig68k** [comment]
That is an error, DTACK_EXT4 should not be connected to the IRQ slot. Thanks, missed that and not tested any boards in slot 4 yet so haven't noticed it. I'll get that one fixed. 

You're correct about the lack of IRQ on slot 4, there wasn't a spare IRQ on the encoder. I had considered putting a shared IRQ on slots 3 and 4, but decided against it.
